name: üé∞ CodeBuild CI/CD Terraform

on:
  push:
    branches:
      - main
    paths:
      - demo-codebuild/**
      - .github/workflows/codebuild.yml
  pull_request:
    branches:
      - main
    paths:
      - demo-codebuild/**
      - .github/workflows/codebuild.yml

env:
  TF_WORKING_DIR: demo-codebuild
  TF_LOG: INFO
  BUCKET_TF_STATE: demo-terraform-backend-state
  TF_WORKSPACE_ENV: "dev"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Cache Terraform
        uses: actions/cache@v4
        id: tf-cache
        with:
          path: |
            ${{ env.TF_WORKING_DIR }}/.terraform
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf','**/*.tfvars','terraform/**') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Setup Git credentials
        run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com
          
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform workspace
        id: workspace
        run: |
          terraform workspace select -or-create=true ${{ env.TF_WORKSPACE_ENV }}
          terraform workspace list
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform plan
        id: plan
        run: |
          terraform plan -input=false -lock=false -out=${{ env.TF_WORKSPACE_ENV }}.tfplan
          terraform show -no-color ${{ env.TF_WORKSPACE_ENV }}.tfplan > ${{ env.TF_WORKSPACE_ENV }}.txt

          {
            echo "plan_${{ env.TF_WORKSPACE_ENV }}<<EOF"
            cat ${{ env.TF_WORKSPACE_ENV }}.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        working-directory: ${{ env.TF_WORKING_DIR }}
        continue-on-error: true

      - uses: actions/github-script@v8
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform plan:\n${{ steps.plan.outputs[format('plan_{0}', env.TF_WORKSPACE_ENV)] }}"
        with:
          script: |
            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Manual Approval
        id: approval
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: troynguyeen
          minimum-approvals: 1
          issue-title: "Deploying CodeBuild Terraform to ${{ env.TF_WORKSPACE_ENV }} on branch ${{ github.ref_name }}"
          issue-body: |
            Approval keywords - "approve", "approved", "lgtm", "yes"
            Denied keywords - "deny", "denied", "no"
          exclude-workflow-initiator-as-approver: false

      - name: Terraform Apply
        if: steps.approval.outputs.approval-status == 'approved'
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}
